
version: "3.5"

# External network
networks:
    ${DOCKER_NETWORK_NAME}:
        external: true

volumes:
    postgres_data:


services:

    # Django app
    django:
        restart: always
        build:
            context: ${ROOT_FOLDER}/api
            dockerfile: ${ROOT_FOLDER}/api/Dockerfile
        expose:
            - ${DJANGO_PORT}
        environment:
            - url=${API_URL}
        command:
            "gunicorn config.wsgi:application --bind 0.0.0.0:${DJANGO_PORT}"
        env_file:
            - ${ROOT_FOLDER}/env/.env.${ENVIRONMENT}
        depends_on:
            - db-rw
        networks:
            - ${DOCKER_NETWORK_NAME}


    # Django database
    db-rw:
        restart: always
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ${ROOT_FOLDER}/env/.env.db
        networks:
            - ${DOCKER_NETWORK_NAME}


    # Task runners
    redis:
        restart: always
        image: "redis:alpine"
        restart: always
        networks:
            - ${DOCKER_NETWORK_NAME}

    celery:
        restart: always
        build:
            context: ${ROOT_FOLDER}/api
            dockerfile: ${ROOT_FOLDER}/api/Dockerfile.celery
        command: celery -A config worker --beat -l info -S django
        env_file:
            - ${ROOT_FOLDER}/env/.env.${ENVIRONMENT}
            - ${ROOT_FOLDER}/env/.env.db
        environment:
            - SQL_HOST=db-rw
            - REDIS_URL=redis://redis:6379/1
        depends_on:
            - db-rw
            - redis
            - django
        networks:
            - ${DOCKER_NETWORK_NAME}


    # Nuxt frontend app
    quasar:
        build: ${ROOT_FOLDER}/frontend/
        ports:
            - "${PORT}:${PORT}"
        environment:
            - url=${ORIGIN_URL}
        volumes:
            - ./frontend:/var/lib/frontend
        command:
            bash -c "cd dist/ssr/ && PORT=${PORT} npm run start"
        env_file:
            - ./env/.env.${ENVIRONMENT}
        networks:
            - ${DOCKER_NETWORK_NAME}
