# Generated by Django 3.1.7 on 2021-03-26 13:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_link', models.CharField(max_length=900, null=True)),
                ('jobsite_link', models.CharField(max_length=300, null=True)),
                ('jobsite', models.CharField(max_length=300, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('company', models.CharField(max_length=300, null=True)),
                ('role', models.CharField(max_length=300, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300, null=True), default=list, size=10)),
            ],
        ),
    ]
