# Generated by Django 3.1.7 on 2021-03-25 16:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300, null=True), default=[], size=10),
        ),
    ]
