name: Run tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.8-slim

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run tests
        run:  apt-get update -y && apt-get install gnupg build-essential python-virtualenv -y && gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.ENV_ENCRYPTION_KEY }} env.tar.gpg | tar -x &&  make test-in-docker
